### ISSUE TITLE
Create Dataset IndexError

### ISSUE THREAD

**Issue by rcaio** [erikbern/deep-fonts#10]
I'm new to python language, I'm trying to create my own dataset so I can use it for training.
I have all the .ttf files inside the folder "scraper/fonts". But when I run create_dataset.py, I get the following error:

_**python create_dataset.py 
Traceback (most recent call last):
  File "create_dataset.py", line 78, in <module>
    for fn in get_ttfs(d=sys.argv[1]):
IndexError: list index out of range**_

Is there a easy solution to that?
Thank you

**Comment by erikbern** [comment]
looks like you need to provide a path on the command line

this might not be the best project to work on if you don't know python – it's quite poorly documented
