### ISSUE TITLE
`fonts.hdf5` no longer available

### ISSUE THREAD

**Issue by silky** [erikbern/deep-fonts#4]
maybe this is on purpose, but this url - https://s3.amazonaws.com/erikbern/fonts.hdf5 - no longer works.

**Comment by erikbern** [comment]
Yeah I removed it – it was causing me like ~$40/month in S3 bills. Let me know if there's another place where I can host it

**Comment by silky** [comment]
maybe google drive?

**Comment by erikbern** [comment]
Yeah true – I'll see if it's free

**Comment by larksq** [comment]
Same request for the fonts.hdf5 since I am working on some similar problems. A lot of big thanks

**Comment by erikbern** [comment]
link should be working now – it's on google drive
