### ISSUE TITLE
could you  share your training data set?

### ISSUE THREAD

**Issue by SHUSHENGQIGUI** [erikbern/deep-fonts#7]
i am so excited to learn about your work about generation of characters. i am a college student,and i am doing this relative work. so i want to learn your finished work by coding .but i can not get the training data. could you share your training data set or website? thank you!!

**Comment by erikbern** [comment]
See the blog post for a link: https://erikbern.com/2016/01/21/analyzing-50k-fonts-using-deep-neural-networks.html
