### ISSUE TITLE
README.md maybe?

### ISSUE THREAD

**Issue by abhinuvpitale** [erikbern/deep-fonts#8]
Extremely interesting project, can you provide a readme or getting started guide?

**Comment by erikbern** [comment]
This project is severely deprecated :)

**Comment by SunHaozhe** [comment]
I think this project is very interesting. Why is it severely deprecated? 

Besides, I did not quite understand where your 40-dimensional font embedding vectors come from. You said that the input of your neural network is a 102-dimensional vector (62-dimensional one-hot vector + 40-dimensional font embedding vector), so you manually defined the font embedding vectors before training the neural network. Is my understanding correct?
